services:
  ccte-api-karate:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV:-dev}
        BASE_URL: ${BASE_URL:-}
        KARATE_TAGS: ${KARATE_TAGS:-@all}
    image: ccte-api-karate:local
    ports:
      - "${PORT:-8080}:8080"
