# This workflow will build a Karate project with Java

# This workflow is set to dispatch based on user input from a drop-down menu.
# Environment defaults to 'prod' and requires no selection. Test requires the choice of a tag before the run can begin.
# The fail-fast setting has been disabled to ensure that the entire test is allowed to complete in the presence of failures.
# This will allow actions to upload an Artifact for viewing regardless of results. Artifacts are labeled Date/Time

name: Karate

on:
  workflow_dispatch:
    inputs:
       env:
        description: 'Environment'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - ctx-local-dev
        - ctx-local-stg

       api:
        description: 'API Selection'             
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - bioactivity
        - chemical
        - exposure
        - hazard
        - html


jobs:

  build:

    runs-on: th878
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:     
    - uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21.0.8'
        distribution: 'temurin'

    - name: Run Karate with Maven
      env:
        API_KEY: ${{ secrets.API_KEY }}
        FAKE_KEY: ${{ secrets.FAKE_KEY }}
        LOCAL_DEV_URL: ${{ secrets.CLD }}
        LOCAL_STG_URL: ${{ secrets.CLS }}
        LOCAL_DEV_HOST: ${{ secrets.HD }}
        LOCAL_STG_HOST: ${{ secrets.HS }}
      run: ./mvnw test -Dkarate.env=${{ inputs.env }} -Dkarate.tags=@${{ inputs.api }},@smoke

    - run: |
           echo 'This Job is running in ${{ inputs.api }} API on the ${{ inputs.env }} environment.' >> $GITHUB_STEP_SUMMARY
    - name: Upload test reports
      uses: actions/upload-artifact@v4.3.1      
      if: ${{ always() }}
      with:
        name: ${{ inputs.api }} Smoke Result
        path: | 
         target/karate-reports

  clean-up:
   runs-on: th878
   needs: build
   steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
