# This workflow will build a Karate project with Java

# This workflow is set to dispatch based on user input from a drop-down menu.
# Environment defaults to 'prod' and requires no selection. Test requires the choice of a tag before the run can begin.
# The fail-fast setting has been disabled to ensure that the entire test is allowed to complete in the presence of failures.
# This will allow actions to upload an Artifact for viewing regardless of results. Artifacts are labeled Date/Time

name: Karate

on:
  workflow_dispatch:
    inputs:
       env:
        description: 'Environment'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - ctx-local-dev
        - ctx-local-stg

       api:
        description: 'API Selection'             
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - bioactivity
        - chemical
        - exposure
        - hazard
        - html


jobs:

  build:

    runs-on: th878
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:     
    - uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21.0.8'
        distribution: 'corretto'
        
    - name: Run Karate with Java
      run: java -Dkey=${{secrets.API_KEY}} -Dfake=${{secrets.FAKE_KEY}} -DlocalDev=${{secrets.CLD}} -DlocalStg=${{secrets.CLS}} -DhostDev=${{secrets.HD}} -DhostStg=${{secrets.HS}} -jar karate-1.4.1.jar -t @${{ inputs.api }} -t @smoke -e ${{ inputs.env }} ccte-api -o ccte-api/target/
    - run: |
           echo 'This Job is running in ${{ inputs.api }} API on the ${{ inputs.env }} environment.' >> $GITHUB_STEP_SUMMARY
           pass=$(scenariospassed ctx-api/target/karate-reports/karate-summary-json.txt)
           fail=$(scenariosfailed ctx-api/target/karate-reports/karate-summary-json.txt)
           echo 'Scenarios Passed: ${pass}📗' >> $GITHUB_STEP_SUMMARY
           echo 'Scenarios Failed: ${fail}📕' >> $GITHUB_STEP_SUMMARY
  result:
    runs-on: th878
    strategy:
      fail-fast: false
    needs: build
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(TZ=":EST" date +'%Y-%m-%d %H.%MEST')" >>$GITHUB_OUTPUT
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1      
      if: ${{ always() }}
      with:
    # Artifact name
        name: ${{ inputs.api }} Smoke Result ${{ steps.date.outputs.date }}
    # A file, directory or wildcard pattern that describes what to upload
        path: | 
         ccte-api/target/karate-reports/karate-summary-json.txt
         ccte-api/target/karate-reports/res
         ccte-api/target/karate-reports/karate-summary.html
         ccte-api/target/karate-reports/karate-labs-logo-ring.svg

  clean-up:
   runs-on: th878
   needs: result
   steps:
    - name: 'Cleanup build folder'
      run: |
        ls -la ./
        rm -rf ./* || true
        rm -rf ./.??* || true
        ls -la ./
