# This workflow will build a Karate project with Java

# This workflow is set to dispatch based on user input from a drop-down menu.
# Environment defaults to 'prod' and requires no selection. Test requires the choice of a tag before the run can begin.
# The fail-fast setting has been disabled to ensure that the entire test is allowed to complete in the presence of failures.
# This will allow actions to upload an Artifact for viewing regardless of results. Artifacts are labeled Date/Time

name: Karate

on:
  workflow_dispatch:
    inputs:
       env:
        description: 'Environment'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - stg
       test:
        description: 'Test scenario tags'
        required: true
        default: 'smoke'
        type: choice
        options:
        - smoke
        - regression
        - data
        - variable
        - cors
        - security

jobs:

  build:

    runs-on: th878
    strategy:
      fail-fast: false
    steps:
    - name: Get current date
      id: date
      run: echo "date=$(TZ=":EST" date +'%Y-%m-%d %H.%MEST')" >>$GITHUB_OUTPUT
      
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        
    - name: Build with Java
      run: java -jar karate-1.4.1.jar -t @${{ inputs.test }} -e @${{ inputs.env }} @$config.apikey{{API_KEY}} ccte-api -o ccte-api/results
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1      
      if: ${{ always() }}
      with:
    # Artifact name
        name: ${{ inputs.test }} Result ${{ steps.date.outputs.date }}
    # A file, directory or wildcard pattern that describes what to upload
        path: ccte-api/results/

